before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/random-dwi/helm-doc/cmd.version={{.Version}} -X github.com/random-dwi/helm-doc/cmd.gitCommit={{.ShortCommit}} -X github.com/random-dwi/helm-doc/cmd.buildTime={{.Date}}
    goos:
      - darwin
      - linux

archives:
  - id: archive
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
    files:
      - LICENSE.md
      - plugin.yaml
      - helm-doc.sh

checksum:
  name_template: 'checksums.txt'

release:
  disable: false
