name: "doc"
version: "0.1.0"
usage: "generate doc for helm chart"
description: |-
  This plugin allows generating doc containing possible configurations of helm charts.
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/helm-doc"
